GET http://localhost:9999/clients/1/extrato

###

POST http://localhost:9999/clients/1/transacoes HTTP/1.1
content-type: application/json

{
  "valor": 1,
  "tipo" : "c",
  "descricao" : "descricao"
}
